name: Test & Publish

on:
  push:
  pull_request:

env:
  GEOPS_KEY: ${{ secrets.GEOPS_KEY }}

jobs:
  build:
    runs-on: macos-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check
      - name: Publish to Maven
        if: github.ref_type == 'tag'
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew publishAndReleaseToMavenCentral
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
